// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using quickOS.Infra.Persistence;

#nullable disable

namespace quickOS.Infra.Persistence.Migrations
{
    [DbContext(typeof(QuickOSDbContext))]
    [Migration("20240523001105_NewEntitiesConfiguration")]
    partial class NewEntitiesConfiguration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("quickOS.Core.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cellphone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character(15)")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uuid");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.HasIndex("Cellphone", "TenantId")
                        .IsUnique();

                    b.HasIndex("Document", "TenantId")
                        .IsUnique();

                    b.HasIndex("Email", "TenantId")
                        .IsUnique();

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("quickOS.Core.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("integer");

                    b.Property<decimal?>("CostPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("ProfitMargin")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("SellingPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("Stock")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<int>("UnitOfMeasurementId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.HasIndex("UnitOfMeasurementId");

                    b.HasIndex("Code", "TenantId")
                        .IsUnique();

                    b.ToTable("Product");
                });

            modelBuilder.Entity("quickOS.Core.Entities.ServiceOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EquipmentDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uuid");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<string>("ProblemDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TechnicalReport")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("TechnicianId")
                        .HasColumnType("integer");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("TechnicianId");

                    b.HasIndex("TenantId");

                    b.HasIndex("Number", "TenantId")
                        .IsUnique();

                    b.ToTable("ServiceOrder");
                });

            modelBuilder.Entity("quickOS.Core.Entities.ServiceOrderProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uuid");

                    b.Property<int>("Item")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<double>("Quantity")
                        .HasPrecision(6, 2)
                        .HasColumnType("double precision");

                    b.Property<int>("ServiceOrderId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("ProductId");

                    b.HasIndex("ServiceOrderId");

                    b.HasIndex("Item", "ServiceOrderId")
                        .IsUnique();

                    b.ToTable("ServiceOrderProduct");
                });

            modelBuilder.Entity("quickOS.Core.Entities.ServiceOrderService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uuid");

                    b.Property<int>("Item")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<double>("Quantity")
                        .HasPrecision(6, 2)
                        .HasColumnType("double precision");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<int>("ServiceOrderId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("ServiceId");

                    b.HasIndex("ServiceOrderId");

                    b.HasIndex("Item", "ServiceOrderId")
                        .IsUnique();

                    b.ToTable("ServiceOrderService");
                });

            modelBuilder.Entity("quickOS.Core.Entities.ServiceProvided", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.HasIndex("Code", "TenantId")
                        .IsUnique();

                    b.ToTable("ServicesProvided");
                });

            modelBuilder.Entity("quickOS.Core.Entities.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("quickOS.Core.Entities.UnitOfMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Abbreviation")
                        .IsUnique();

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("UnitsOfMeasurement");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "un",
                            CreatedAt = new DateTime(2024, 5, 23, 0, 11, 4, 652, DateTimeKind.Utc).AddTicks(1798),
                            ExternalId = new Guid("ff047f1a-f3bf-46bc-ba53-98cb0ed0818e"),
                            IsActive = true,
                            Name = "Unidade",
                            UpdatedAt = new DateTime(2024, 5, 23, 0, 11, 4, 652, DateTimeKind.Utc).AddTicks(1798)
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "pç",
                            CreatedAt = new DateTime(2024, 5, 23, 0, 11, 4, 652, DateTimeKind.Utc).AddTicks(1811),
                            ExternalId = new Guid("efc06679-387c-4418-9864-eb7490b7e65d"),
                            IsActive = true,
                            Name = "Peça",
                            UpdatedAt = new DateTime(2024, 5, 23, 0, 11, 4, 652, DateTimeKind.Utc).AddTicks(1811)
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "cx",
                            CreatedAt = new DateTime(2024, 5, 23, 0, 11, 4, 652, DateTimeKind.Utc).AddTicks(1819),
                            ExternalId = new Guid("11ac42c7-c08b-48af-91b1-e72131089a3f"),
                            IsActive = true,
                            Name = "Caixa",
                            UpdatedAt = new DateTime(2024, 5, 23, 0, 11, 4, 652, DateTimeKind.Utc).AddTicks(1819)
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "pa",
                            CreatedAt = new DateTime(2024, 5, 23, 0, 11, 4, 652, DateTimeKind.Utc).AddTicks(1827),
                            ExternalId = new Guid("f7f5301b-fc1c-42e3-9b8d-270f2021760e"),
                            IsActive = true,
                            Name = "Par",
                            UpdatedAt = new DateTime(2024, 5, 23, 0, 11, 4, 652, DateTimeKind.Utc).AddTicks(1828)
                        },
                        new
                        {
                            Id = 5,
                            Abbreviation = "cm",
                            CreatedAt = new DateTime(2024, 5, 23, 0, 11, 4, 652, DateTimeKind.Utc).AddTicks(1835),
                            ExternalId = new Guid("6895c981-724b-49d9-9bf6-88d3a383d1d7"),
                            IsActive = true,
                            Name = "Centímetro",
                            UpdatedAt = new DateTime(2024, 5, 23, 0, 11, 4, 652, DateTimeKind.Utc).AddTicks(1835)
                        },
                        new
                        {
                            Id = 6,
                            Abbreviation = "m",
                            CreatedAt = new DateTime(2024, 5, 23, 0, 11, 4, 652, DateTimeKind.Utc).AddTicks(1843),
                            ExternalId = new Guid("b9602136-b0c8-49d8-adb5-23395d05c1bc"),
                            IsActive = true,
                            Name = "Metro",
                            UpdatedAt = new DateTime(2024, 5, 23, 0, 11, 4, 652, DateTimeKind.Utc).AddTicks(1843)
                        },
                        new
                        {
                            Id = 7,
                            Abbreviation = "g",
                            CreatedAt = new DateTime(2024, 5, 23, 0, 11, 4, 652, DateTimeKind.Utc).AddTicks(1851),
                            ExternalId = new Guid("c1555e76-5b31-4b70-ae4d-d75be6c77f4f"),
                            IsActive = true,
                            Name = "Grama",
                            UpdatedAt = new DateTime(2024, 5, 23, 0, 11, 4, 652, DateTimeKind.Utc).AddTicks(1851)
                        },
                        new
                        {
                            Id = 8,
                            Abbreviation = "kg",
                            CreatedAt = new DateTime(2024, 5, 23, 0, 11, 4, 652, DateTimeKind.Utc).AddTicks(1859),
                            ExternalId = new Guid("b56ccd37-dd24-482a-8c60-8825e6608749"),
                            IsActive = true,
                            Name = "Quilograma",
                            UpdatedAt = new DateTime(2024, 5, 23, 0, 11, 4, 652, DateTimeKind.Utc).AddTicks(1859)
                        },
                        new
                        {
                            Id = 9,
                            Abbreviation = "ml",
                            CreatedAt = new DateTime(2024, 5, 23, 0, 11, 4, 652, DateTimeKind.Utc).AddTicks(1867),
                            ExternalId = new Guid("f25ad949-c0f5-486b-a9c1-9774bd163533"),
                            IsActive = true,
                            Name = "Mililitro",
                            UpdatedAt = new DateTime(2024, 5, 23, 0, 11, 4, 652, DateTimeKind.Utc).AddTicks(1867)
                        },
                        new
                        {
                            Id = 10,
                            Abbreviation = "l",
                            CreatedAt = new DateTime(2024, 5, 23, 0, 11, 4, 652, DateTimeKind.Utc).AddTicks(1875),
                            ExternalId = new Guid("a5b91309-573a-4ce8-add9-768dcfd2bbfb"),
                            IsActive = true,
                            Name = "Litro",
                            UpdatedAt = new DateTime(2024, 5, 23, 0, 11, 4, 652, DateTimeKind.Utc).AddTicks(1875)
                        });
                });

            modelBuilder.Entity("quickOS.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CellPhone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character(15)")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uuid");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RefreshToken")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RefreshTokenExpiresIn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CellPhone")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("RefreshToken")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("quickOS.Core.Entities.Customer", b =>
                {
                    b.HasOne("quickOS.Core.Entities.Tenant", "Tenant")
                        .WithMany("Customers")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("quickOS.Core.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<int>("CustomerId")
                                .HasColumnType("integer");

                            b1.Property<string>("City")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("Details")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("Neighborhood")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("Number")
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)");

                            b1.Property<string>("State")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("Street")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("ZipCode")
                                .HasMaxLength(9)
                                .HasColumnType("character(9)")
                                .IsFixedLength();

                            b1.HasKey("CustomerId");

                            b1.ToTable("Customer");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.Navigation("Address");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("quickOS.Core.Entities.Product", b =>
                {
                    b.HasOne("quickOS.Core.Entities.Tenant", "Tenant")
                        .WithMany("Products")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("quickOS.Core.Entities.UnitOfMeasurement", "UnitOfMeasurement")
                        .WithMany("Products")
                        .HasForeignKey("UnitOfMeasurementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("UnitOfMeasurement");
                });

            modelBuilder.Entity("quickOS.Core.Entities.ServiceOrder", b =>
                {
                    b.HasOne("quickOS.Core.Entities.Customer", "Customer")
                        .WithMany("ServiceOrders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("quickOS.Core.Entities.User", "Technician")
                        .WithMany("ServiceOrders")
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("quickOS.Core.Entities.Tenant", "Tenant")
                        .WithMany("ServiceOrders")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Technician");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("quickOS.Core.Entities.ServiceOrderProduct", b =>
                {
                    b.HasOne("quickOS.Core.Entities.Product", "Product")
                        .WithMany("ServiceOrderProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("quickOS.Core.Entities.ServiceOrder", "ServiceOrder")
                        .WithMany("Products")
                        .HasForeignKey("ServiceOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ServiceOrder");
                });

            modelBuilder.Entity("quickOS.Core.Entities.ServiceOrderService", b =>
                {
                    b.HasOne("quickOS.Core.Entities.ServiceProvided", "Service")
                        .WithMany("ServiceOrderServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("quickOS.Core.Entities.ServiceOrder", "ServiceOrder")
                        .WithMany("Services")
                        .HasForeignKey("ServiceOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");

                    b.Navigation("ServiceOrder");
                });

            modelBuilder.Entity("quickOS.Core.Entities.ServiceProvided", b =>
                {
                    b.HasOne("quickOS.Core.Entities.Tenant", "Tenant")
                        .WithMany("ServicesProvided")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("quickOS.Core.Entities.User", b =>
                {
                    b.HasOne("quickOS.Core.Entities.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("quickOS.Core.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("integer");

                            b1.Property<string>("City")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("Details")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("Neighborhood")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("Number")
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)");

                            b1.Property<string>("State")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("Street")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("ZipCode")
                                .HasMaxLength(9)
                                .HasColumnType("character(9)")
                                .IsFixedLength();

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Address");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("quickOS.Core.Entities.Customer", b =>
                {
                    b.Navigation("ServiceOrders");
                });

            modelBuilder.Entity("quickOS.Core.Entities.Product", b =>
                {
                    b.Navigation("ServiceOrderProducts");
                });

            modelBuilder.Entity("quickOS.Core.Entities.ServiceOrder", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("quickOS.Core.Entities.ServiceProvided", b =>
                {
                    b.Navigation("ServiceOrderServices");
                });

            modelBuilder.Entity("quickOS.Core.Entities.Tenant", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("Products");

                    b.Navigation("ServiceOrders");

                    b.Navigation("ServicesProvided");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("quickOS.Core.Entities.UnitOfMeasurement", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("quickOS.Core.Entities.User", b =>
                {
                    b.Navigation("ServiceOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
